GET http://localhost:3000/api/tasks/all

###
POST http://localhost:3000/api/tasks/
Content-Type: application/json

{
  "title":"Tarea 3!",
  "description":"Descripcion de la tarea 3"
}

###
GET http://localhost:3000/api/tasks/fZrrnjA6JgaRZcbFG-tda
Content-Type: application/json
